//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("jvbsl")]
[assembly: AssemblyProduct("engenious")]
[assembly: AssemblyVersion("0.2.0.0")]
[assembly: AssemblyFileVersion("0.2.0")]
[assembly: AssemblyInformationalVersion("0.2.0-unstable.6+Branch.develop.Sha.0dfaf7bc96dba3a4e5e0882a4c6d1fe7c5e52b44")]
[assembly: AssemblyCopyright("Copyright (c) jvbsl 2016")]
[assembly: AssemblyConfiguration("Release")]

