//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("jvbsl")]
[assembly: AssemblyProduct("engenious")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0-unstable.81+Branch.develop.Sha.4e57dcef458695dc0b2f72af3bbe9579bad7f342")]
[assembly: AssemblyCopyright("Copyright (c) jvbsl 2016")]
[assembly: AssemblyConfiguration("Release")]

