// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ContentTool
{
    
    #region Windows Form Designer generated code
    public partial class frmMain
    {
        private void InitializeComponent()
        {
            this.splitContainer = new System.Windows.Forms.SplitContainer();
            this.treeContentFiles = new System.Windows.Forms.TreeView();
            this.txtLog = new System.Windows.Forms.RichTextBox();
            this.newMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.openMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.closeMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.importMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.saveAsMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.fileMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.undoMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.redoMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.newItemMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.newFolderMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.existingItemMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.existingFolderMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.addMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.renameMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.deleteMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.buildMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.rebuildMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.cleanMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.cancelMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.buildMainMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mainMenu = new System.Windows.Forms.MenuStrip();
            this.imgList = new System.Windows.Forms.ImageList();
            this.splitContainer.Panel1.SuspendLayout();
            this.splitContainer.Panel2.SuspendLayout();
            this.splitContainer.SuspendLayout();
            // 
            // splitContainer
            // 
            this.splitContainer.AutoScrollOffset = new System.Drawing.Point(0, 0);
            this.splitContainer.Dock = System.Windows.Forms.DockStyle.Fill;
            // 
            // splitContainer.Panel1
            // 
            this.splitContainer.Panel1.Text = "Panel1";
            this.splitContainer.Panel1.Controls.Add(this.treeContentFiles);
            // 
            // splitContainer.Panel2
            // 
            this.splitContainer.Panel2.Text = "Panel2";
            this.splitContainer.Panel2.Controls.Add(this.txtLog);
            this.splitContainer.SplitterDistance = 97;
            this.splitContainer.TabStop = false;
            this.splitContainer.Text = "splitContainer";
            this.splitContainer.Location = new System.Drawing.Point(0, 22);
            this.splitContainer.Name = "splitContainer";
            this.splitContainer.Size = new System.Drawing.Size(292, 251);
            this.splitContainer.TabIndex = 0;
            // 
            // treeContentFiles
            // 
            this.treeContentFiles.BackColor = System.Drawing.SystemColors.Window;
            this.treeContentFiles.ForeColor = System.Drawing.SystemColors.WindowText;
            this.treeContentFiles.Indent = 19;
            this.treeContentFiles.ItemHeight = 16;
            this.treeContentFiles.Text = "treeContentFiles";
            this.treeContentFiles.LineColor = System.Drawing.Color.FromArgb(255, 86, 86, 86);
            this.treeContentFiles.ImageList = imgList;
            this.treeContentFiles.ImageKey = null;
            this.treeContentFiles.SelectedImageKey = null;
            this.treeContentFiles.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treeContentFiles.Name = "treeContentFiles";
            this.treeContentFiles.Size = new System.Drawing.Size(97, 251);
            this.treeContentFiles.TabIndex = 0;
            this.treeContentFiles.LabelEdit = true;
            this.treeContentFiles.AfterLabelEdit += TreeContentFiles_AfterLabelEdit;
            this.treeContentFiles.BeforeLabelEdit += TreeContentFiles_BeforeLabelEdit;
            // 
            // txtLog
            // 
            this.txtLog.ForeColor = System.Drawing.SystemColors.WindowText;
            this.txtLog.ZoomFactor = 1F;
            this.txtLog.BackColor = System.Drawing.SystemColors.Window;
            this.txtLog.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLog.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtLog.Name = "txtLog";
            this.txtLog.Size = new System.Drawing.Size(191, 251);
            this.txtLog.TabIndex = 0;
            // 
            // newMenuItem
            // 
            this.newMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.newMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.newMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.newMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.newMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.newMenuItem.Image = null;
            this.newMenuItem.ImageIndex = -1;
            this.newMenuItem.ImageKey = "";
            this.newMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.newMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.newMenuItem.Name = "";
            this.newMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.newMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.newMenuItem.Size = new System.Drawing.Size(57, 19);
            this.newMenuItem.Text = "New...";
            this.newMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.newMenuItem.ToolTipText = null;
            this.newMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N;
            this.newMenuItem.Click += NewMenuItem_Click;
            // 
            // openMenuItem
            // 
            this.openMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.openMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.openMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.openMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.openMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.openMenuItem.Image = null;
            this.openMenuItem.ImageIndex = -1;
            this.openMenuItem.ImageKey = "";
            this.openMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.openMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.openMenuItem.Name = "";
            this.openMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.openMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.openMenuItem.Size = new System.Drawing.Size(63, 19);
            this.openMenuItem.Text = "Open...";
            this.openMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.openMenuItem.ToolTipText = null;
            this.openMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.O;
            this.openMenuItem.Click += OpenMenuItem_Click;
            // 
            // closeMenuItem
            // 
            this.closeMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.closeMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.closeMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.closeMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.closeMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.closeMenuItem.Image = null;
            this.closeMenuItem.ImageIndex = -1;
            this.closeMenuItem.ImageKey = "";
            this.closeMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.closeMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.closeMenuItem.Name = "";
            this.closeMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.closeMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.closeMenuItem.Size = new System.Drawing.Size(64, 19);
            this.closeMenuItem.Text = "Close...";
            this.closeMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.closeMenuItem.ToolTipText = null;
            this.closeMenuItem.Click += CloseMenuItem_Click;
            // 
            // importMenuItem
            // 
            this.importMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.importMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.importMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.importMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.importMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.importMenuItem.Image = null;
            this.importMenuItem.ImageIndex = -1;
            this.importMenuItem.ImageKey = "";
            this.importMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.importMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.importMenuItem.Name = "";
            this.importMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.importMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.importMenuItem.Size = new System.Drawing.Size(70, 19);
            this.importMenuItem.Text = "Import...";
            this.importMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.importMenuItem.ToolTipText = null;
            this.importMenuItem.Click += ImportMenuItem_Click;
            // 
            // saveMenuItem
            // 
            this.saveMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.saveMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.saveMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.saveMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.saveMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.saveMenuItem.Image = null;
            this.saveMenuItem.ImageIndex = -1;
            this.saveMenuItem.ImageKey = "";
            this.saveMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.saveMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.saveMenuItem.Name = "";
            this.saveMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.saveMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.saveMenuItem.Size = new System.Drawing.Size(49, 19);
            this.saveMenuItem.Text = "Save";
            this.saveMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.saveMenuItem.ToolTipText = null;
            this.saveMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.S;
            this.saveMenuItem.Click += SaveMenuItem_Click;
            // 
            // saveAsMenuItem
            // 
            this.saveAsMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.saveAsMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.saveAsMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.saveAsMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.saveAsMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.saveAsMenuItem.Image = null;
            this.saveAsMenuItem.ImageIndex = -1;
            this.saveAsMenuItem.ImageKey = "";
            this.saveAsMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.saveAsMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.saveAsMenuItem.Name = "";
            this.saveAsMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.saveAsMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.saveAsMenuItem.Size = new System.Drawing.Size(79, 19);
            this.saveAsMenuItem.Text = "Save As...";
            this.saveAsMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.saveAsMenuItem.ToolTipText = null;
            this.saveAsMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift | System.Windows.Forms.Keys.S;
            this.saveAsMenuItem.Click += SaveAsMenuItem_Click;
            // 
            // exitMenuItem
            // 
            this.exitMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.exitMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.exitMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.exitMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.exitMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.exitMenuItem.Image = null;
            this.exitMenuItem.ImageIndex = -1;
            this.exitMenuItem.ImageKey = "";
            this.exitMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.exitMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.exitMenuItem.Name = "";
            this.exitMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.exitMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.exitMenuItem.Size = new System.Drawing.Size(42, 19);
            this.exitMenuItem.Text = "Exit";
            this.exitMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.exitMenuItem.ToolTipText = null;
            this.exitMenuItem.Click += ExitMenuItem_Click;
            // 
            // fileMenuItem
            // 
            this.fileMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.fileMenuItem.DropDownItems.Add(this.newMenuItem);
            this.fileMenuItem.DropDownItems.Add(this.openMenuItem);
            this.fileMenuItem.DropDownItems.Add(this.closeMenuItem);
            this.fileMenuItem.DropDownItems.Add("-");
            this.fileMenuItem.DropDownItems.Add(this.importMenuItem);
            this.fileMenuItem.DropDownItems.Add("-");
            this.fileMenuItem.DropDownItems.Add(this.saveMenuItem);
            this.fileMenuItem.DropDownItems.Add(this.saveAsMenuItem);
            this.fileMenuItem.DropDownItems.Add("-");
            this.fileMenuItem.DropDownItems.Add(this.exitMenuItem);
            this.fileMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.fileMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.fileMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.fileMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.fileMenuItem.Image = null;
            this.fileMenuItem.ImageIndex = -1;
            this.fileMenuItem.ImageKey = "";
            this.fileMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.fileMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.fileMenuItem.Name = "";
            this.fileMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.fileMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.fileMenuItem.Size = new System.Drawing.Size(40, 18);
            this.fileMenuItem.Text = "&File";
            this.fileMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.fileMenuItem.ToolTipText = null;
            this.fileMenuItem.DropDownOpening += FileMenuItem_DropDownOpening;
            // 
            // undoMenuItem
            // 
            this.undoMenuItem.Enabled = false;
            this.undoMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.undoMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.undoMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.undoMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.undoMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.undoMenuItem.Image = null;
            this.undoMenuItem.ImageIndex = -1;
            this.undoMenuItem.ImageKey = "";
            this.undoMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.undoMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.undoMenuItem.Name = "";
            this.undoMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.undoMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.undoMenuItem.Size = new System.Drawing.Size(50, 19);
            this.undoMenuItem.Text = "Undo";
            this.undoMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.undoMenuItem.ToolTipText = null;
            this.undoMenuItem.Click += UndoMenuItem_Click;
            // 
            // redoMenuItem
            // 
            this.redoMenuItem.Enabled = false;
            this.redoMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.redoMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.redoMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.redoMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.redoMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.redoMenuItem.Image = null;
            this.redoMenuItem.ImageIndex = -1;
            this.redoMenuItem.ImageKey = "";
            this.redoMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.redoMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.redoMenuItem.Name = "";
            this.redoMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.redoMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.redoMenuItem.Size = new System.Drawing.Size(50, 19);
            this.redoMenuItem.Text = "Redo";
            this.redoMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.redoMenuItem.ToolTipText = null;
            this.redoMenuItem.Click += RedoMenuItem_Click;
            // 
            // newItemMenuItem
            // 
            this.newItemMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.newItemMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.newItemMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.newItemMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.newItemMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.newItemMenuItem.Image = null;
            this.newItemMenuItem.ImageIndex = -1;
            this.newItemMenuItem.ImageKey = "";
            this.newItemMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.newItemMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.newItemMenuItem.Name = "";
            this.newItemMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.newItemMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.newItemMenuItem.Size = new System.Drawing.Size(86, 19);
            this.newItemMenuItem.Text = "New Item...";
            this.newItemMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.newItemMenuItem.ToolTipText = null;
            this.newItemMenuItem.Click += NewItemMenuItem_Click;
            this.newItemMenuItem.Enabled = false;
            // 
            // newFolderMenuItem
            // 
            this.newFolderMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.newFolderMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.newFolderMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.newFolderMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.newFolderMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.newFolderMenuItem.Image = null;
            this.newFolderMenuItem.ImageIndex = -1;
            this.newFolderMenuItem.ImageKey = "";
            this.newFolderMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.newFolderMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.newFolderMenuItem.Name = "";
            this.newFolderMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.newFolderMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.newFolderMenuItem.Size = new System.Drawing.Size(96, 19);
            this.newFolderMenuItem.Text = "New Folder...";
            this.newFolderMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.newFolderMenuItem.ToolTipText = null;
            this.newFolderMenuItem.Click += NewFolderMenuItem_Click;
            // 
            // existingItemMenuItem
            // 
            this.existingItemMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.existingItemMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.existingItemMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.existingItemMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.existingItemMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.existingItemMenuItem.Image = null;
            this.existingItemMenuItem.ImageIndex = -1;
            this.existingItemMenuItem.ImageKey = "";
            this.existingItemMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.existingItemMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.existingItemMenuItem.Name = "";
            this.existingItemMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.existingItemMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.existingItemMenuItem.Size = new System.Drawing.Size(106, 19);
            this.existingItemMenuItem.Text = "Existing Item...";
            this.existingItemMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.existingItemMenuItem.ToolTipText = null;
            this.existingItemMenuItem.Click += ExistingItemMenuItem_Click;
            // 
            // existingFolderMenuItem
            // 
            this.existingFolderMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.existingFolderMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.existingFolderMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.existingFolderMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.existingFolderMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.existingFolderMenuItem.Image = null;
            this.existingFolderMenuItem.ImageIndex = -1;
            this.existingFolderMenuItem.ImageKey = "";
            this.existingFolderMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.existingFolderMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.existingFolderMenuItem.Name = "";
            this.existingFolderMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.existingFolderMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.existingFolderMenuItem.Size = new System.Drawing.Size(116, 19);
            this.existingFolderMenuItem.Text = "Existing Folder...";
            this.existingFolderMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.existingFolderMenuItem.ToolTipText = null;
            this.existingFolderMenuItem.Click += ExistingFolderMenuItem_Click;
            // 
            // addMenuItem
            // 
            this.addMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.addMenuItem.DropDownItems.Add(this.newItemMenuItem);
            this.addMenuItem.DropDownItems.Add(this.newFolderMenuItem);
            this.addMenuItem.DropDownItems.Add("-");
            this.addMenuItem.DropDownItems.Add(this.existingItemMenuItem);
            this.addMenuItem.DropDownItems.Add(this.existingFolderMenuItem);
            this.addMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.addMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.addMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.addMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.addMenuItem.Image = null;
            this.addMenuItem.ImageIndex = -1;
            this.addMenuItem.ImageKey = "";
            this.addMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.addMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.addMenuItem.Name = "";
            this.addMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.addMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.addMenuItem.Size = new System.Drawing.Size(43, 19);
            this.addMenuItem.Text = "Add";
            this.addMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.addMenuItem.ToolTipText = null;
            // 
            // renameMenuItem
            // 
            this.renameMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.renameMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.renameMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.renameMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.renameMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.renameMenuItem.Image = null;
            this.renameMenuItem.ImageIndex = -1;
            this.renameMenuItem.ImageKey = "";
            this.renameMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.renameMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.renameMenuItem.Name = "";
            this.renameMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.renameMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.renameMenuItem.Size = new System.Drawing.Size(68, 19);
            this.renameMenuItem.Text = "Rename";
            this.renameMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.renameMenuItem.ToolTipText = null;
            this.renameMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F2;
            this.renameMenuItem.Click += RenameMenuItem_Click;
            // 
            // deleteMenuItem
            // 
            this.deleteMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.deleteMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.deleteMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.deleteMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.deleteMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.deleteMenuItem.Image = null;
            this.deleteMenuItem.ImageIndex = -1;
            this.deleteMenuItem.ImageKey = "";
            this.deleteMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.deleteMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.deleteMenuItem.Name = "";
            this.deleteMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.deleteMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.deleteMenuItem.Size = new System.Drawing.Size(57, 19);
            this.deleteMenuItem.Text = "Delete";
            this.deleteMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.deleteMenuItem.ToolTipText = null;
            this.deleteMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Delete;
            this.deleteMenuItem.Click += DeleteMenuItem_Click;
            // 
            // editMenuItem
            // 
            this.editMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.editMenuItem.DropDownItems.Add(this.undoMenuItem);
            this.editMenuItem.DropDownItems.Add(this.redoMenuItem);
            this.editMenuItem.DropDownItems.Add("-");
            this.editMenuItem.DropDownItems.Add(this.addMenuItem);
            this.editMenuItem.DropDownItems.Add("-");
            this.editMenuItem.DropDownItems.Add(this.renameMenuItem);
            this.editMenuItem.DropDownItems.Add("-");
            this.editMenuItem.DropDownItems.Add(this.deleteMenuItem);
            this.editMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.editMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.editMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.editMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.editMenuItem.Image = null;
            this.editMenuItem.ImageIndex = -1;
            this.editMenuItem.ImageKey = "";
            this.editMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.editMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.editMenuItem.Name = "";
            this.editMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.editMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.editMenuItem.Size = new System.Drawing.Size(42, 18);
            this.editMenuItem.Text = "Edit";
            this.editMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.editMenuItem.ToolTipText = null;
            this.editMenuItem.DropDownOpening += EditMenuItem_DropDownOpening;
            // 
            // buildMenuItem
            // 
            this.buildMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.buildMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.buildMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.buildMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.buildMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.buildMenuItem.Image = null;
            this.buildMenuItem.ImageIndex = -1;
            this.buildMenuItem.ImageKey = "";
            this.buildMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.buildMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.buildMenuItem.Name = "";
            this.buildMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.buildMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.buildMenuItem.Size = new System.Drawing.Size(49, 19);
            this.buildMenuItem.Text = "Build";
            this.buildMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.buildMenuItem.ToolTipText = null;
            this.buildMenuItem.ShortcutKeys = System.Windows.Forms.Keys.F8;
            this.buildMenuItem.Click += BuildMenuItem_Click;
            // 
            // rebuildMenuItem
            // 
            this.rebuildMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.rebuildMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.rebuildMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.rebuildMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.rebuildMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.rebuildMenuItem.Image = null;
            this.rebuildMenuItem.ImageIndex = -1;
            this.rebuildMenuItem.ImageKey = "";
            this.rebuildMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.rebuildMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.rebuildMenuItem.Name = "";
            this.rebuildMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.rebuildMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.rebuildMenuItem.Size = new System.Drawing.Size(63, 19);
            this.rebuildMenuItem.Text = "Rebuild";
            this.rebuildMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.rebuildMenuItem.ToolTipText = null;
            this.rebuildMenuItem.ShortcutKeys = System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.F8;
            this.rebuildMenuItem.Click += RebuildMenuItem_Click;
            // 
            // cleanMenuItem
            // 
            this.cleanMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.cleanMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.cleanMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.cleanMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.cleanMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cleanMenuItem.Image = null;
            this.cleanMenuItem.ImageIndex = -1;
            this.cleanMenuItem.ImageKey = "";
            this.cleanMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.cleanMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.cleanMenuItem.Name = "";
            this.cleanMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.cleanMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.cleanMenuItem.Size = new System.Drawing.Size(53, 19);
            this.cleanMenuItem.Text = "Clean";
            this.cleanMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.cleanMenuItem.ToolTipText = null;
            this.cleanMenuItem.Click += CleanMenuItem_Click;
            // 
            // cancelMenuItem
            // 
            this.cancelMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.cancelMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.cancelMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.cancelMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.cancelMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.cancelMenuItem.Image = null;
            this.cancelMenuItem.ImageIndex = -1;
            this.cancelMenuItem.ImageKey = "";
            this.cancelMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.cancelMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.cancelMenuItem.Name = "";
            this.cancelMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.cancelMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.cancelMenuItem.Size = new System.Drawing.Size(91, 19);
            this.cancelMenuItem.Text = "Cancel Build";
            this.cancelMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.cancelMenuItem.ToolTipText = null;
            this.cancelMenuItem.Enabled = false;
            this.cancelMenuItem.Click += CancelMenuItem_Click;
            // 
            // buildMainMenuItem
            // 
            this.buildMainMenuItem.Enabled = false;
            this.buildMainMenuItem.DropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.AboveLeft;
            this.buildMainMenuItem.DropDownItems.Add(this.buildMenuItem);
            this.buildMainMenuItem.DropDownItems.Add(this.rebuildMenuItem);
            this.buildMainMenuItem.DropDownItems.Add(this.cleanMenuItem);
            this.buildMainMenuItem.DropDownItems.Add(this.cancelMenuItem);
            this.buildMainMenuItem.BackColor = System.Drawing.SystemColors.Control;
            this.buildMainMenuItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.ImageAndText;
            this.buildMainMenuItem.Font = new System.Drawing.Font("DejaVu Sans", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.buildMainMenuItem.ForeColor = System.Drawing.SystemColors.ControlText;
            this.buildMainMenuItem.Image = null;
            this.buildMainMenuItem.ImageIndex = -1;
            this.buildMainMenuItem.ImageKey = "";
            this.buildMainMenuItem.ImageTransparentColor = System.Drawing.Color.Empty;
            this.buildMainMenuItem.Margin = new System.Windows.Forms.Padding(0);
            this.buildMainMenuItem.Name = "";
            this.buildMainMenuItem.Padding = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.buildMainMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Inherit;
            this.buildMainMenuItem.Size = new System.Drawing.Size(49, 18);
            this.buildMainMenuItem.Text = "Build";
            this.buildMainMenuItem.TextDirection = System.Windows.Forms.ToolStripTextDirection.Horizontal;
            this.buildMainMenuItem.ToolTipText = null;
            this.buildMainMenuItem.DropDownOpening += BuildMainMenuItem_DropDownOpening;
            // 
            // mainMenu
            // 
            this.mainMenu.DefaultDropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.BelowRight;
            this.mainMenu.GripMargin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.mainMenu.ImageScalingSize = new System.Drawing.Size(16, 16);
            this.mainMenu.Items.Add(this.fileMenuItem);
            this.mainMenu.Items.Add(this.editMenuItem);
            this.mainMenu.Items.Add(this.buildMainMenuItem);
            this.mainMenu.LayoutStyle = System.Windows.Forms.ToolStripLayoutStyle.HorizontalStackWithOverflow;
            this.mainMenu.RenderMode = System.Windows.Forms.ToolStripRenderMode.ManagerRenderMode;
            this.mainMenu.Name = "mainMenu";
            this.mainMenu.Size = new System.Drawing.Size(292, 22);
            this.mainMenu.TabIndex = 1;
            this.mainMenu.Text = "mainMenu";
            //
            // imgList
            //
            this.imgList.ColorDepth = System.Windows.Forms.ColorDepth.Depth32Bit;
            this.imgList.Images.Add("project", new System.Drawing.Bitmap(System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("project")));
            this.imgList.Images.Add("folder", new System.Drawing.Bitmap(System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("folder")));

            // 
            // frmMain
            // 
            this.ClientSize = new System.Drawing.Size(292, 273);
            this.Text = "Content Pipeline";
            this.Controls.Add(this.splitContainer);
            this.Controls.Add(this.mainMenu);
            this.Name = "frmMain";
            this.splitContainer.Panel1.ResumeLayout(false);
            this.splitContainer.Panel2.ResumeLayout(false);
            this.splitContainer.ResumeLayout(false);
            this.FormClosing += FrmMain_FormClosing;
            this.Load += FrmMain_Load;

        }
        //private System.Windows.Forms.PropertyGrid prpItem;
        private System.Windows.Forms.ImageList imgList;
        private System.Windows.Forms.SplitContainer splitContainer;
        private System.Windows.Forms.TreeView treeContentFiles;
        private System.Windows.Forms.RichTextBox txtLog;
        private System.Windows.Forms.ToolStripMenuItem newMenuItem;
        private System.Windows.Forms.ToolStripMenuItem openMenuItem;
        private System.Windows.Forms.ToolStripMenuItem closeMenuItem;
        private System.Windows.Forms.ToolStripMenuItem importMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveAsMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fileMenuItem;
        private System.Windows.Forms.ToolStripMenuItem undoMenuItem;
        private System.Windows.Forms.ToolStripMenuItem redoMenuItem;
        private System.Windows.Forms.ToolStripMenuItem newItemMenuItem;
        private System.Windows.Forms.ToolStripMenuItem newFolderMenuItem;
        private System.Windows.Forms.ToolStripMenuItem existingItemMenuItem;
        private System.Windows.Forms.ToolStripMenuItem existingFolderMenuItem;
        private System.Windows.Forms.ToolStripMenuItem addMenuItem;
        private System.Windows.Forms.ToolStripMenuItem renameMenuItem;
        private System.Windows.Forms.ToolStripMenuItem deleteMenuItem;
        private System.Windows.Forms.ToolStripMenuItem editMenuItem;
        private System.Windows.Forms.ToolStripMenuItem buildMenuItem;
        private System.Windows.Forms.ToolStripMenuItem rebuildMenuItem;
        private System.Windows.Forms.ToolStripMenuItem cleanMenuItem;
        private System.Windows.Forms.ToolStripMenuItem cancelMenuItem;
        private System.Windows.Forms.ToolStripMenuItem buildMainMenuItem;
        private System.Windows.Forms.MenuStrip mainMenu;
    }
    #endregion
}
